import {Platform, StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    height: '100%',
    backgroundColor: '#FFFFFF',
  },
  topTextPosition: {
    fontSize: 16,
    fontFamily: 'GoodTimesRg-Bold',
    color: '#FFFFFF',
    marginBottom: 6,
  },
  topTextDetails: {
    fontSize: 16,
    fontFamily: 'Montserrat-Bold',
    color: '#FFFFFF',
    marginBottom: 8,
    lineHeight: 16.3,
  },
  background: {
    overflow: 'hidden',
    width: '100%',
    height: '100%',
  },
  header: {
    marginTop: 38,
    flexDirection: 'column',
    justifyContent: 'center',
    paddingTop: Platform.OS === 'ios' ? 20 : 0,
  },
  headerOptions: {
    marginTop: 9,
    paddingHorizontal: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerOptionsTextBackground: {
    justifyContent: 'center',
    width: 76,
    height: 32,
    borderRadius: 30,
  },
  headerOptionsText: {
    textAlign: 'center',
    fontFamily: 'Montserrat-Bold',
    fontWeight: '600',
    fontSize: 18,
    lineHeight: 22,
    color: '#FFFFFF',
  },
  headerLeadearboard: {},
  headerLeaderboardPositionsText: {},
  headerLeaderboardUsername: {},
  headerLeaderboardTime: {},
  body: {
    marginTop: 0,
    flex: 1,
    width: '100%',
  },
  button: {
    height: 37,
    borderWidth: 1.5,
    borderRadius: 10,
    borderColor: '#E0E0E0',
    backgroundColor: '#FFFFFF',
  },
  buttonLabel: {
    fontFamily: 'Montserrat-SemiBold',
    fontWeight: '500',
    fontSize: 15,
    lineHeight: 18.62,
    color: '#979696',
  },
  dropdownStyle: {
    borderWidth: 1,
    borderColor: '#A79C9C',
    borderRadius: 6,
  },
  rowStyle: {
    fontFamily: 'Montserrat-SemiBold',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 18.62,
    color: '#979696',
  },
  bodyLeaderboard: {
    marginBottom: 2,
    height: 66,
    borderRadius: 23,
  },
  userPosition: {
    marginVertical: 24,
    fontFamily: 'GoodTimesRg-Bold',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 16.3,
  },
  userName: {
    fontFamily: 'Montserrat-Bold',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20,
    textAlignVertical: 'center',
  },
  userTime: {
    marginTop: 24,
    fontFamily: 'Montserrat-Bold',
    fontWeight: '600',
    fontSize: 18,
    lineHeight: 18.62,
  },
});
